"""Regenerate tests/golden/legacy_0_goldens.json (or v1_goldens.json with --version 1).

Run ONLY against code whose legacy-0 behaviour you intend to freeze (the file in
the repository was generated from the unmodified pre-T7 snapshot):

    python -m tests.golden.generate_legacy_goldens             # legacy-0 (never regenerate casually)
    python -m tests.golden.generate_legacy_goldens --version 1 # v1 regression freeze
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import platform
import sys
from pathlib import Path

import numpy as np

from tests.golden.scenarios import build_all

ROOT = Path(__file__).resolve().parents[2]
OUTS = {"legacy-0": "legacy_0_goldens.json", "1": "v1_goldens.json"}
HASHED = ["src/digital_twin.py", "src/optimizer.py", "api/services/twin_service.py", "src/carbon_provider.py"]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", default="legacy-0", choices=sorted(OUTS))
    version = parser.parse_args().version
    out = Path(__file__).with_name(OUTS[version])
    meta = {
        "physics_version": version,
        "commit": "unknown - no .git in snapshot",
        "sha256": {p: hashlib.sha256((ROOT / p).read_bytes()).hexdigest() for p in HASHED},
        "python": platform.python_version(),
        "numpy": np.__version__,
        "generated": datetime.date.today().isoformat(),
        "note": (
            "Frozen from the unmodified pre-T7 snapshot. Floats are exact reprs; compared with rel 1e-9."
            if version == "legacy-0"
            else "v1 REGRESSION FREEZE generated by the T7 implementation: it detects change, it does not validate the physics "
            "(the invariants in tests/test_physics_v1_invariants.py do that)."
        ),
    }
    out.write_text(json.dumps({"meta": meta, **build_all(version)}, indent=1, sort_keys=True))
    print("wrote", out, "|", out.stat().st_size, "bytes", file=sys.stderr)


if __name__ == "__main__":
    main()
